# Generated by Django 4.0.6 on 2022-07-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut_link',
            options={'verbose_name': 'Элемент ссылки', 'verbose_name_plural': 'Сокращенные ссылки:'},
        ),
    ]
