# Generated by Django 4.0.6 on 2022-07-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_form', '0002_alter_shortcut_link_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcut_link',
            name='link_short',
        ),
    ]
