# Generated by Django 4.0.6 on 2022-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_form', '0003_remove_shortcut_link_link_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut_link',
            name='link_short',
            field=models.CharField(default=0, max_length=51, verbose_name='Конечная ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortcut_link',
            name='link_info',
            field=models.CharField(max_length=51, verbose_name='Начальная ссылка'),
        ),
        migrations.AlterField(
            model_name='shortcut_link',
            name='user_info',
            field=models.CharField(max_length=51, verbose_name='Пользователь'),
        ),
    ]
